# Generated by Django 5.0.6 on 2024-08-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fantasy_data",
            "0006_teamperformance_rb_points_teamperformance_te_points_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamperformance",
            name="projected_wins",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
