# Generated by Django 5.0.6 on 2024-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0007_alter_teamperformance_projected_wins"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamperformance",
            name="margin",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
