# Generated by Django 4.2.13 on 2025-06-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0008_teamperformance_margin"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamperformance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teamperformance",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterUniqueTogether(
            name="teamperformance",
            unique_together={("team_name", "week", "year")},
        ),
    ]
