# Generated by Django 4.2.13 on 2025-07-31 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0009_alter_teamperformance_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yahoo_player_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                ("nfl_team", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_team", models.CharField(blank=True, max_length=100, null=True)),
                ("to_team", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("TRADE", "Trade"),
                            ("PICKUP", "Waiver/FA Pickup"),
                            ("DROP", "Drop to Waiver"),
                            ("DRAFT", "Draft"),
                        ],
                        max_length=20,
                    ),
                ),
                ("week", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fantasy_data.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fantasy_team", models.CharField(max_length=100)),
                ("week", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                (
                    "roster_status",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("BENCH", "Bench"),
                            ("WAIVER", "Waiver Wire"),
                            ("FREE_AGENT", "Free Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fantasy_data.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "fantasy_team", "week", "year")},
            },
        ),
        migrations.CreateModel(
            name="PlayerPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fantasy_team", models.CharField(max_length=100)),
                ("week", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("points_scored", models.FloatField()),
                ("was_started", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fantasy_data.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "week", "year")},
            },
        ),
    ]
