# Generated by Django 4.2.13 on 2025-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0010_player_playertransaction_playerroster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerroster",
            name="fantasy_team",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="playerroster",
            name="week",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="playerroster",
            name="year",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="teamperformance",
            name="team_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teamperformance",
            name="week",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="teamperformance",
            name="year",
            field=models.IntegerField(db_index=True, default=2023),
        ),
        migrations.AddIndex(
            model_name="playerroster",
            index=models.Index(
                fields=["fantasy_team", "year"], name="fantasy_dat_fantasy_fc3bbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerroster",
            index=models.Index(
                fields=["year", "week"], name="fantasy_dat_year_afb586_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamperformance",
            index=models.Index(
                fields=["team_name", "year"], name="fantasy_dat_team_na_c00529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamperformance",
            index=models.Index(
                fields=["year", "week"], name="fantasy_dat_year_90d096_idx"
            ),
        ),
    ]
