# Generated by Django 5.0.6 on 2025-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0011_alter_playerroster_fantasy_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectedPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_key", models.CharField(db_index=True, max_length=32)),
                ("week", models.PositiveIntegerField(db_index=True)),
                ("player_id", models.PositiveIntegerField(db_index=True)),
                ("player_name", models.CharField(blank=True, max_length=128)),
                ("position", models.CharField(blank=True, max_length=16)),
                ("team_key", models.CharField(blank=True, max_length=32)),
                (
                    "projected_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("projected_raw", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="yahoo", max_length=16)),
                ("pulled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["league_key", "week"],
                        name="fantasy_dat_league__5f00ac_idx",
                    ),
                    models.Index(
                        fields=["player_id", "week"],
                        name="fantasy_dat_player__be5dbe_idx",
                    ),
                ],
                "unique_together": {("league_key", "player_id", "week", "source")},
            },
        ),
    ]
