# Generated by Django 5.0.6 on 2025-09-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0012_projectedpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamOwnerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(db_index=True, max_length=100)),
                ("owner_name", models.CharField(max_length=100)),
                ("year", models.IntegerField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team_name", "year"],
                        name="fantasy_dat_team_na_285219_idx",
                    ),
                    models.Index(
                        fields=["owner_name", "year"],
                        name="fantasy_dat_owner_n_e122e3_idx",
                    ),
                ],
                "unique_together": {("team_name", "year")},
            },
        ),
    ]
