# Generated by Django 5.0.6 on 2026-07-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0013_teamownermapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMatchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("week", models.PositiveIntegerField()),
                ("team_a", models.CharField(max_length=100)),
                ("team_b", models.CharField(max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["year", "week"], name="fantasy_dat_year_f6511c_idx"
                    )
                ],
                "unique_together": {("year", "week", "team_a", "team_b")},
            },
        ),
    ]
