# Generated by Django 5.0.6 on 2026-08-02 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0014_scheduledmatchup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playertransaction",
            name="transaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="playertransaction",
            name="week",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
