# Generated by Django 4.2.13 on 2025-07-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengescore",
            name="click_speed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challengescore",
            name="coin_streak",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challengescore",
            name="number_guesses",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
