# Generated by Django 5.0.6 on 2025-07-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0002_challengescore_click_speed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengescore",
            name="typing_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
