# Generated by Django 4.2.13 on 2025-07-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0004_punishmentvote_punishmentranking"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="punishmentranking",
            unique_together={("vote", "punishment_index"), ("vote", "rank")},
        ),
    ]
