# Generated by Django 4.2.13 on 2025-07-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0005_alter_punishmentranking_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChallengeScore",
        ),
    ]
