# Generated by Django 4.2.13 on 2025-07-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0006_delete_challengescore"),
    ]

    operations = [
        migrations.CreateModel(
            name="WheelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("punishment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
