# Generated by Django 4.2.13 on 2025-08-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0007_wheelresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("punishment", models.TextField(blank=True)),
                ("kept_teams", models.JSONField(default=list)),
                ("must_keep_next", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
