# Generated by Django 4.2.13 on 2025-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0008_bucketsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketsession",
            name="is_test_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bucketsession",
            name="week_number",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="BucketWeekResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("punishment", models.TextField()),
                ("kept_teams", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("week_number",)},
            },
        ),
    ]
