# Generated by Django 4.2.13 on 2025-08-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "draftgame",
            "0009_bucketsession_is_test_mode_bucketsession_week_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketsession",
            name="current_player",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bucketsession",
            name="selected_team",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
