# Generated by Django 4.2.13 on 2025-08-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0010_bucketsession_current_player_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketTeamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("player_name", models.CharField(max_length=100)),
                ("is_win", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "week_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_results",
                        to="draftgame.bucketweekresult",
                    ),
                ),
            ],
        ),
    ]
