# Generated by Django 4.2.13 on 2026-06-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0015_season_loser_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bucketweekresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bucketsession",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_sessions",
                to="draftgame.season",
            ),
        ),
        migrations.AddField(
            model_name="bucketweekresult",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bucket_weeks",
                to="draftgame.season",
            ),
        ),
        migrations.AddField(
            model_name="wheelresult",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wheel_results",
                to="draftgame.season",
            ),
        ),
        migrations.AlterField(
            model_name="bucketsession",
            name="session_key",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name="bucketsession",
            unique_together={("session_key", "season")},
        ),
        migrations.AlterUniqueTogether(
            name="bucketweekresult",
            unique_together={("season", "week_number")},
        ),
    ]
