# Generated by Django 4.2.13 on 2026-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0018_season_grid_finalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="punishment",
            name="is_finalist",
            field=models.BooleanField(
                default=False,
                help_text="Locked in (via Finalize voting) as part of the season's wheel/grid set.",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="wheel_size",
            field=models.IntegerField(
                default=12,
                help_text="How many top-voted punishments are locked in as the season's wheel/grid set.",
            ),
        ),
    ]
