# Generated by Django 4.2.23 on 2026-07-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0019_finalist_and_wheel_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="submissions_close_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, submissions automatically close at this time even while submissions_open is on.",
                null=True,
            ),
        ),
    ]
