# Generated by Django 4.2.23 on 2026-07-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0020_season_submissions_close_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="punishment",
            name="is_duplicate",
            field=models.BooleanField(
                default=False,
                help_text="Consolidated as a duplicate of an earlier submission. Stays visible on the suggestion list but is excluded from voting.",
            ),
        ),
    ]
