# Generated by Django 5.0.6 on 2026-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draftgame", "0021_punishment_is_duplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="bucket_open",
            field=models.BooleanField(
                default=False,
                help_text="When set, Bucket of Death is live and visible to the whole league (staff can always see it).",
            ),
        ),
    ]
